version: "3"
services:
  bridgeserver:
    build: .
    env_file:
       - server.env
    image: bridgeserver
    ports:
      - "3000:3000"
      - "6080:6080"
    deploy:
      restart_policy:
        condition: on-failure

