version: "3"
services:
  bridgeserver:
    build: .
    env_file:
       - server.env
    image: bridgeserver
    volumes:
      - ./credentials.json:/credentials.json
    ports:
      - "6080:6080"
    deploy:
      restart_policy:
        condition: on-failure

