version: "3"
services:
  bridgeserver:
    build: .
    env_file:
       - .env
    image: bridgeserver
    ports:
      - ${BRIDGE_PORT}:3000
      - ${SERVICE_PORT}:6080
    deploy:
      restart_policy:
        condition: on-failure

