version: "3"
services:
  bridgeserver:
    build: .
    env_file:
       - server.env
    image: bridgeserver
    ports:
      - "3002:3002"
      - "6080:6080"
    volumes:
      - /home/adriana/resources/usp_lab_files:/app/lab_files
    deploy:
      restart_policy:
        condition: on-failure

